name: Node.js CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - name: Publish
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm publish --ignore-scripts --access public --tag latest
          curl -X POST --silent ${EDGE_URL}
          curl -X POST --silent ${STABLE_URL}
        env:
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          EDGE_URL: ${{ secrets.EDGE_URL }}
          STABLE_URL: ${{ secrets.STABLE_URL }}
